locomotion/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.contrib.auth import views 


urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^',include('moving.urls')),
    url(r'^accounts/', include('registration.backends.simple.urls')),
    url(r'^logout/$', views.logout, {"next_page": '/'}),
]

moving/urls.py
from django.conf.urls import url
from . import views

from django.conf import settings
from django.conf.urls.static import static
urlpatterns=[
    url('^$',views.home,name = 'home'),
    url(r'^edit$', views.edit, name='edit_profile'),
    url(r'^rate/',views.rate_site, name='rate'),
    url(r'^booking(?P<service_id>\d+)',views.book, name='booking'),
    url(r'^ajax/newsletter/$', views.newsletter, name='newsletter'),
    url(r'^add(?P<service_id>\d+)',views.add, name='add'),
    url(r'^drop/(?P<service_id>\d+)',views.drop, name='drop'),
    url(r'^one_service(?P<service_id>\d+)',views.service, name='service'),
]
if settings.DEBUG:
    urlpatterns+= static(settings.MEDIA_URL, document_root = settings.MEDIA_ROOT)

moving/models.py
from django.db import models
from django.contrib.auth.models import User
import datetime as dt
from django.db.models.signals import post_save
from django.dispatch import receiver


@receiver(post_save, sender=User)
def create_user_profile(sender, instance, created, **kwargs):
    if created:
        Profile.objects.create(user=instance)


@receiver(post_save, sender=User)
def save_user_profile(sender, instance, **kwargs):
    instance.profile.save()


        
class Profile(models.Model):
    Profile_photo = models.ImageField(upload_to = 'images/',blank=True)
    Bio = models.TextField(max_length = 50)
    user = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)
    service = models.ForeignKey('Services', related_name='services',null=True)

    def save_profile(self):
        self.save()

    @classmethod
    def get_by_id(cls, id):
        details = Profile.objects.get(user = id)
        return details

    @classmethod
    def filter_by_id(cls, id):
        details = Profile.objects.filter(user = id).first()
        return details
    
    @classmethod
    def search_user(cls, name):
        userprof = Profile.objects.filter(user__username__icontains = name)
        return userprof

        
class Rate(models.Model):
    efficiency = models.TextField(max_length = 50,null=True)
    care = models.TextField(max_length = 50,null=True)
    response = models.TextField(max_length = 50,null=True)
    average = models.TextField(max_length = 50,null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)
    
  
    def __str__(self):
        return self.design

    # class Meta:
    #     ordering = ['id']

    def save_rate(self):
        self.save()

    @classmethod
    def get_rate(cls, profile):
        rate = Rate.objects.filter(Profile__pk = profile)
        return rate
    
    @classmethod
    def get_all_rating(cls):
        rating = Rate.objects.all()
        return rating

class Payment(models.Model):
    pay = models.CharField(max_length=30)
    user = models.ForeignKey(User,related_name='user',null=True)

    def save_service(self):
        self.save()
    
    @classmethod
    def get_payment(cls, service):
        pay = Payment.objects.filter(service__pk = service)
        return pay

class Booking(models.Model):
    location = models.CharField(max_length = 50,null=True)
    number = models.CharField(max_length = 50,null=True)
    email = models.CharField(max_length = 50,null=True)
    user = models.OneToOneField(User,on_delete=models.CASCADE, primary_key=True)
    payment = models.ForeignKey(Payment,related_name='booking',null=True)

    def save_service(self):
        self.save()

class Services(models.Model):
    screenshot = models.ImageField(upload_to = 'images/',null=True)
    service_name = models.CharField(max_length =50,null=True)
    profile = models.ForeignKey(Profile, null = True,related_name='project')
    pub_date = models.DateTimeField(auto_now_add=True, null=True)
    user= models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    description = models.CharField(max_length =60,null=True)
    payment = models.ForeignKey('Payment',related_name='payment',null=True)

    class Meta:
        ordering = ['-pk']

    def save_service(self):
        self.save()
    
    @classmethod
    def get_service(cls, profile):
        project = Services.objects.filter(Profile__pk = profile)
        return project
    
    @classmethod
    def get_all_services(cls):
        project = Services.objects.all()
        return project

  
    @classmethod
    def find_service_id(cls, id):
        identity = Services.objects.get(pk=id)
        return identity

class NewsLetterRecipients(models.Model):
    name = models.CharField(max_length = 30)
    email = models.EmailField()

class Comment(models.Model):
    name = models.CharField(max_length=30)
    service = models.ForeignKey(Services,related_name='comment')
    user = models.ForeignKey(User,null=True)


    def __str__(self):
        return self.name

    class Meta:
        ordering = ['-id']

    def save_comment(self):
        self.save()

    def delete_comment(self):
        self.delete()

    @classmethod
    def find_commentpost(cls,id):
        comments = Comments.objects.filter(post__pk = id)
        return comments

    

moving/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Profile,Rate,Services,Payment,Comment,Booking

class ProfileForm(forms.ModelForm):
    class Meta:
        model = Profile
        exclude = ['user','service']

class RateForm(forms.ModelForm):
    class Meta:
        model = Rate
        exclude =['user']
class ServiceForm(forms.ModelForm):
    class Meta:
        model = Services
        exclude = ['user','profile']

class NewsLetterForm(forms.Form):
    your_name = forms.CharField(label='First Name',max_length=30)
    email = forms.EmailField(label='Email')
 
class CommentForm(forms.Form):
    class Meta:
        model = Comment
        exclude = ['user','service']

class PaymentForm(forms.Form):
    class Meta:
        model = Payment
        exclude = ['user']

class BookingForm(forms.ModelForm):
    class Meta:
        model = Booking
        exclude = ['user','payment']

moving/views.py
from django.shortcuts import render,redirect,get_object_or_404
from django.http import HttpResponse,HttpResponseRedirect
from .forms import ProfileForm,RateForm,NewsLetterForm,CommentForm,PaymentForm,BookingForm
from django.contrib.auth.decorators import login_required
from django.contrib.auth.models import User
import datetime as dt
from .models import NewsLetterRecipients,Profile,Rate,Services,Payment, Booking
from .email import send_welcome_email
from django.http import JsonResponse

# Create your views here.

def convert_dates(dates):
    # function that gets the weekday number for the date.
    day_number = dt.date.weekday(dates)

    days = ['Monday','Tuesday','Wednesday','thursday','Friday','Saturday','Sunday']
    '''
    Returns the actual day of the week
    '''
    day = days[day_number]
    return day


def home(request):
    rateform = RateForm()
    form = NewsLetterForm()
    date = dt.date.today()
    service = Services.objects.all()
    print(service)
    return render(request,'main/home.html', locals())

'''
logs out current user from account
'''
def logout(request):
    return render(request, 'main_pages/home.html')

@login_required(login_url='/accounts/login/')
def profile(request):
    profile = User.objects.get(username=request.user)
    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            edit = form.save(commit=False)
            edit.user = request.user
            edit.save()
            return redirect('edit_profile')
    else:
        form = ProfileForm()
    return render(request, 'profile/edit_profile.html', locals())

@login_required(login_url='/accounts/login')
def rate_site(request):
    profile = User.objects.get(username=request.user)
    if request.method == 'POST':
        rateform = RateForm(request.POST, request.FILES)
        print(rateform.errors)
        if rateform.is_valid():
            rating = rateform.save(commit=False)
            rating.user = request.user
            rating.save()
            return redirect('home')
    else:
        rateform = RateForm()
    return render(request,'main/home.html',locals())

def newsletter(request):
    name = request.POST.get('your_name')
    email = request.POST.get('email')

    recipient = NewsLetterRecipients(name=name, email=email)
    recipient.save()
    send_welcome_email(name, email)
    data = {'success': 'You have been successfully added to mailing list'}
    return JsonResponse(data)

def view_project(request):
    service = Services.objects.all()
    return render(request,'home.html', locals())

@login_required(login_url='/accounts/login')
def add(request,service_id):
    service = Services.objects.get(id=service_id)
    current_user = request.user
    current_user.profile.service = service
    current_user.profile.save()
    return redirect('service',service_id)

@login_required(login_url='/accounts/login')
def drop(request,service_id):
    current_user = request.user
    current_user.profile.service = None
    current_user.profile.save()
    return redirect('home')

@login_required(login_url='/accounts/login/')
def service(request,service_id):
    current_user = request.user
    name = current_user.profile.service
    single_service = Services.objects.get(id = request.user.profile.service.id)
    # comments = Comment.objects.all()
    # form = CommentForm(instance=request.user)

    return render(request,'main/service.html',locals())

@login_required(login_url='/accounts/login/')
def edit(request):
    profile = User.objects.get(username=request.user)

    if request.method == 'POST':
        form = ProfileForm(request.POST, request.FILES)
        if form.is_valid():
            edit = form.save(commit=False)
            edit.user = request.user
            edit.save()
            return redirect('edit_profile')
    else:
        form = ProfileForm()
    return render(request, 'profile/edit_profile.html', locals())

@login_required(login_url='/accounts/login/')
def book(request,service_id):
    profile = User.objects.get(username=request.user)
    service = Services.objects.get(id=service_id)
    single_service = Services.objects.get(id = request.user.profile.service.id)
    if request.method == 'POST':
        bookingform = BookingForm(request.POST, request.FILES)
        if bookingform.is_valid():
            edit = bookingform.save(commit=False)
            edit.user = request.user
            edit.save()
            return redirect('home')
    else:
        bookingform = BookingForm()
    return render(request, 'main/payment.html', locals())


@login_required(login_url='/accounts/login/')
def bookingform(request,service_id):
    service = Services.objects.get(id=service_id)
    bookingform = BookingForm()
    # bookingform = ProfileForm()
    single_service = Services.objects.get(id = request.user.profile.service.id)
    return render(request,'main/payment.html',  {'bookingform':bookingform, 'single_service':single_service})

moving/templates/main/home.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{{ block.super }}
<div class="container-fluid" id="main">

    <div class="modal" tabindex="-1" id="myModal" role="dialog">
        <div class="modal-dialog" role="document">
            <div class="modal-content" id="rating">
                <div class="modal-header">
                    <h5 class="text-center" style="font-family: 'Sail', cursive;">LocoMotion</h5>
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                    </button>
                </div>
                <div class="modal-body">
                    <form id="questions">
                        <div class="row">
                            <div class="col-md-2">
                                efficiency.
                            </div>

                            <div class="col-md-10">
                                <input type="radio" name="rate1" id="terrible" checked="checked" value="terrible">Terrible
                                <input type="radio" name="rate1" id="poor" value="poor">Poor
                                <input type="radio" name="rate1" id="average" value="average">Average
                                <input type="radio" name="rate1" id="very good" value="very good">Very Good
                                <input type="radio" name="rate1" id="excellent" value="excellent">Excellent

                            </div>
                        </div>


                        <br>
                        <div class="row">
                            </br>
                            <div class="col-md-2">
                                time.
                            </div>

                            <div class="col-md-10">
                                <input type="radio" name="rate2" id="terrible" checked="checked" value="terrible">Terrible
                                <input type="radio" name="rate2" id="poor" value="poor">Poor
                                <input type="radio" name="rate2" id="average" value="average">Average
                                <input type="radio" name="rate2" id="very good" value="very good">Very Good
                                <input type="radio" name="rate2" id="excellent" value="excellent">Excellent

                            </div>
                        </div>

                        <br>
                        <div class="row">
                            </br>
                            <div class="col-md-2">
                                response.
                            </div>

                            <div class="col-md-10">
                                <input type="radio" name="rate3" id="terrible" checked="checked" value="terrible">Terrible
                                <input type="radio" name="rate3" id="poor" value="poor">Poor
                                <input type="radio" name="rate3" id="average" value="average">Average
                                <input type="radio" name="rate3" id="very good" value="very good">Very Good
                                <input type="radio" name="rate3" id="excellent" value="excellent">Excellent

                            </div>
                        </div>

                        <br>
                        <button class="btn btn-outline-success" type="submit" id="submit" name="reset_form" value="Reset Form"
                            onclick="this.form.reset();">SUBMIT</button>
                    </form>
                    <div id="divhidden" style="display: none;">
                        <div class="col-md-8">
                            <form action="{% url 'rate'%}" method="POST" enctype="multipart/form-data" id="ratingform">
                                {% csrf_token %}
                                {% bootstrap_form rateform %}
                                <input type="submit" class="btn btn-outline-success" value="Upload">
                            </form>
                        </div>
                    </div>
                </div>
                <div class="modal-footer">

                    <button type="button" class="btn btn-outline-danger btn-bg" data-dismiss="modal" data-toggle="tooltip"
                        data-placement="right" title="Close Single Image">Close</button>
                    <br>
                </div>
            </div>

        </div>

    </div>
    <div>
        <h1 style="text-align:center;font-family: 'Sail', cursive; text-align: center;color: white;">LocoMotion <br>  We Move You.</h1>
    </div>
    {% if request.user.profile.service %}
    <div class="row">
        <div class="col-md-2"></div>
        <div class="col-md-8">
            <a style="color:white;" href="{% url 'service' service_id=request.user.profile.service.id %}" class="btn btn-outline-dark"><i class="fa fa-shopping-cart" style="font-size:24px"></i> View
                Cart</a>
        </div>
        <div class="col-md-2"></div>
    </div>
    {% endif %}

    <div class="row">
        {% for data in service %}
        <a href="{% url 'add' service_id=data.id %}" style="font-size: 12px;text-decoration:none;font-family: 'Julius Sans One', sans-serif;">
            <figure class="snip0019">
                <img src="{{data.screenshot.url}}" alt="sample11" height="200px;" width="300px;" />
                <figcaption>
                    <div>
                        <h2 style="font-size: 12px;font-family: 'Julius Sans One', sans-serif;">{{data.service_name}}</h2>
                    </div>
                    <div>
                        <p style="font-size:12px;font-family: 'Julius Sans One', sans-serif;">{{data.description}}<br>Ksh {{data.payment.pay}}</p>
                    </div>
                </figcaption>
            </figure><br>
            <button class="btn btn-outline-secondary" style="font-size: 11px;margin-left: 80px;color:white;"><i class="fa fa-shopping-cart" style="font-size:24px"></i> Add to Cart<br>Ksh {{data.payment.pay}}</button>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock %}

moving/templates/main/mail.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{{ block.super }}
<div class="container fluid">
        <form action="{%url 'home' %}" id='kkk' method="post">
            {%csrf_token%}
    
            {% bootstrap_form form layout='inline' %}
            <button type="submit" value="Subscribe"></button>
        </form>
    </div>
    <script>
    $(document).ready(function(){
        $('form').submit(function(event){
          event.preventDefault()
          form = $("form")
      
          $.ajax({
            'url':'/ajax/newsletter/',
            'type':'POST',
            'data':form.serialize(),
            'dataType':'json',
            'success': function(data){
              alert(data['success'])
            },
          })// END of Ajax method
          $('#id_your_name').val('')
          $("#id_email").val('')
        }) // End of submit event
      
      }) // End of document ready function
    </script>
{% endblock %}

moving/templates/main/payment.html
{%extends 'base.html'%}
{% load bootstrap4 %}

{% block content %}
<div class="container-fluid" id="book" >
    <div class="jumbotron" id="bookingform">
        <div class="row">
            <div class="col-md-2"></div>
            <div class="col-md-8" id="business">
                <form action="{% url 'booking' service_id=single_service.id %}" method="POST" enctype="multipart/form-data">
                    <h1 style="text-align:center;font-family: 'Sail', cursive; text-align: center;color: white;">LocoMotion <br>  We Move You.</h1>
                    {% csrf_token %}
                    {% bootstrap_form bookingform %}
                    <input type="submit" class="btn btn-success" value="Finish Payment">
                </form>
            </div>
            <div class="col-md-2"></div>
        </div>
    </div>
</div>
{% endblock %}

moving/templates/main/service.html
{% extends 'base.html' %}
{% load bootstrap4 %}
{% block content %}
{{ block.super }}
<div class="container-fluid" id="single-service">
    <figure class="snip1206">
        <img src="{{single_service.screenshot.url}} " alt="service" style="margin-top: 10px;">
        <figcaption>
            <h2 style="text-align:center;font-family: 'Sail', cursive;">LocoMotion</h2>
            <p>We move you.</p>
        </figcaption>
        <a href="#"></a>
    </figure>

    <!-- <img src="{{single_service.screenshot.url}}" alt="service" style="margin-top: 10px;"> -->
    <div class="row">
        <div class="col l4">
            <div class="z-depth-1 order-detail-cards">
                <h6 class="center-align">Your Order</h6>
                <h5 class="center-align">{{single_service.service_name}}</h5>
            </div>
        </div>

        <div class="col l4">
            <div class="z-depth-1 order-detail-cards">
                <h6 class="center-align">Plan</h6>
                <h5 class="center-align">{{single_service.description}}</h5>
            </div>
        </div>

        <div class="col l4">
            <div class="z-depth-1 order-detail-cards">
                <h6 class="center-align">Price</h6>
                <h5 class="center-align">ksh {{single_service.payment.pay}}</h5>
            </div>
        </div>
    </div>
    <a href="{% url 'drop' service_id=single_service.id %}" class="btn btn-outline-danger"><i class="fa fa-shopping-cart" style="font-size:24px"></i> Remove From Cart</a>
    <a href="{% url 'booking' service_id=single_service.id %}" class="btn btn-outline-success">Proceed to payment</a>

</div>

{% endblock %}